### ISSUE TITLE
trait not satisfied?

### ISSUE THREAD

**Issue by eerz** [ImplFerris/esp32-book#2]
okay so I was following the WiFi section of the book, im at the 9.1 and I followed everything properly, but i dont understand why im getting this trait bound error even though the code is exactly the same:

```the trait bound `esp_wifi::wifi::WifiDevice<'_>: smoltcp::phy::Device` is not satisfied```

![Image](https://github.com/user-attachments/assets/b16b670d-b7b6-4bd6-9f26-0f2ec3840236)

here is my code so far: 

```rs
#![no_std]
#![no_main]

use blocking_network_stack::Stack;
// presets
use defmt::{info, println};
use esp_hal::clock::CpuClock;
use esp_hal::{ main, time };
use esp_hal::time::{ Duration, Instant };
use esp_hal::timer::timg::TimerGroup;
use esp_println as _;

// self added
use esp_hal::rng::Rng;
use esp_hal::peripherals::Peripherals;
use esp_wifi::wifi::{self, WifiController};
use smoltcp::iface::{ SocketSet, SocketStorage };
use smoltcp::wire::DhcpOption;


#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {
    }
}

extern crate alloc;

const SSID: &str = "SSID";
const PASSWORD: &str = "PASSWORD";

#[main]
fn main() -> ! {
    // generator version: 0.3.1

    let peripherals = init_hardware();
    let timg0 = TimerGroup::new(peripherals.TIMG0);
    let mut rng = Rng::new(peripherals.RNG);

    // First, we initialize the WiFi controller using a hardware timer, RNG, and clock peripheral.
    let esp_wifi_ctrl = esp_wifi::init(timg0.timer0, rng.clone(), peripherals.RADIO_CLK).unwrap();

    // Next, we create a WiFi driver instance (controller to manage connections and interfaces for network modes).
    let (mut controller, interfaces) = esp_wifi::wifi
        ::new(&esp_wifi_ctrl, peripherals.WIFI)
        .unwrap();

    // Finally, we configure the device to use station (STA) mode , allowing it to connect to WiFi networks as a client.
    let mut device = interfaces.sta;

    // We will create a SocketSet with storage for up to 3 sockets to manage multiple sockets, such as DHCP and TCP, within the stack.
    let mut socket_set_entries: [SocketStorage; 3] = Default::default();
    let mut socket_set = SocketSet::new(&mut socket_set_entries[..]);

    let mut dhcp_socket = smoltcp::socket::dhcpv4::Socket::new();

    // we can set a hostname here (or add other DHCP options)
    dhcp_socket.set_outgoing_options(
        &[
            DhcpOption {
                kind: 12,
                data: b"implRust",
            },
        ]
    );
    socket_set.add(dhcp_socket);

    let now = || time::Instant::now().duration_since_epoch().as_millis();
    let mut stack = Stack::new(
        create_interface(&mut device),
        device,
        socket_set,
        now,
        rng.random()
    );

    wifi::Configuration::Client(wifi::ClientConfiguration {
        ssid: SSID.try_into().unwrap(),
        password: PASSWORD.try_into().unwrap(),
        ..Default::default()
    });

    let res = controller.set_configuration(&client_config);
    info!("wifi_set_configuration returned {:?}", res);

    // Start the wifi controller
    controller.start().unwrap();

    loop {
        info!("Hello world!");
        let delay_start = Instant::now();
        while delay_start.elapsed() < Duration::from_millis(500) {}
    }

    // for inspiration have a look at the examples at https://github.com/esp-rs/esp-hal/tree/esp-hal-v1.0.0-beta.0/examples/src/bin
}

fn init_hardware() -> Peripherals {
    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);
    esp_alloc::heap_allocator!(size: 72 * 1024);
    peripherals
}

fn scan_wifi(controller: &mut WifiController<'_>) {
    info!("Start Wifi Scan");
    let res: Result<(heapless::Vec<_, 10>, usize), _> = controller.scan_n();
    if let Ok((res, _count)) = res {
        for ap in res {
            info!("{:?}", ap);
        }
    }
}

fn connect_wifi(
    controller: &mut WifiController<'_>,
    stack: &mut Stack<'_, esp_wifi::wifi::WifiDevice<'_>>
) {
    println!("{:?}", controller.capabilities());
    info!("wifi_connect {:?}", controller.connect());

    info!("Wait to get connected");
    loop {
        match controller.is_connected() {
            Ok(true) => {
                break;
            }
            Ok(false) => {}
            Err(err) => panic!("{:?}", err),
        }
    }
    info!("Connected: {:?}", controller.is_connected());

    info!("Wait for IP address");
    loop {
        stack.work();
        if stack.is_iface_up() {
            println!("IP acquired: {:?}", stack.get_ip_info());
            break;
        }
    }
}

fn obtain_ip(stack: &mut Stack<'_, esp_wifi::wifi::WifiDevice<'_>>) {
    info!("Wait for IP address");
    loop {
        stack.work();
        if stack.is_iface_up() {
            println!("IP acquired: {:?}", stack.get_ip_info());
            break;
        }
    }
}
```

here is my Cargo.toml: 

```toml
[package]
edition = "2021"
name    = "wifi-webfetch"
version = "0.1.0"

[[bin]]
name = "wifi-webfetch"
path = "./src/bin/main.rs"

[dependencies]
blocking-network-stack = { git = "https://github.com/bjoernQ/blocking-network-stack.git", rev = "b3ecefc222d8806edd221f266999ca339c52d34e", default-features = false, features = [
  "dhcpv4",
  "tcp",
] }
critical-section = "1.2.0"
defmt = "0.3.10"
embassy-net = { version = "0.6.0", features = [
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = "0.6.1"
esp-alloc = "0.7.0"
esp-hal = { version = "1.0.0-beta.0", features = [
  "defmt",
  "esp32",
  "unstable",
] }
esp-println = { version = "0.13.0", features = ["defmt-espflash", "esp32"] }
esp-wifi = { version = "0.13.0", features = [
  "builtin-scheduler",
  "defmt",
  "esp-alloc",
  "esp32",
  "wifi",
] }
heapless = { version = "0.8.0", default-features = false }
smoltcp = { version = "0.12.0", default-features = false, features = [
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
```
